@{
    Description = "Generated by WinSpec"
    Name = "WinSpec Configuration"
    Providers = @(
        "Registry"
        "Feature"
    )
    Trigger = @("PackageInstall")
    TriggerConfig = @{
        PackageInstall = @{
            Roles = @("base", "dev", "backup", "utils")
        }
    }
    Registry =
    @{
        Clipboard =
        @{
            EnableHistory = $true
        }
        Desktop =
        @{
            ForegroundLockTimeout = 0
            MenuShowDelay = "400"
        }
        Explorer =
        @{
            ShowFileExt = $true
            ShowHidden = $true
        }
        Start =
        @{
            ShowRecentlyAddedApps = $false
            ShowRecommendations = $false
        }
        Taskbar =
        @{
            ShowTaskViewButton = $true
            ShowWidgets = $false
        }
        Theme =
        @{
            AppTheme = "dark"
            SystemTheme = "dark"
        }
    }
}
