# Profiles Config for Clash Verge

current: R8gZjmES6YI5
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1756019175
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1756019175
- uid: m17flY2wkJGN
  type: merge
  name: null
  file: m17flY2wkJGN.yaml
  updated: 1757387542
- uid: s1KfOCTWvLUn
  type: script
  name: null
  file: s1KfOCTWvLUn.js
  updated: 1757387542
- uid: rsv811pc6MtC
  type: rules
  name: null
  file: rsv811pc6MtC.yaml
  updated: 1757387542
- uid: pIenP4XtQ3kW
  type: proxies
  name: null
  file: pIenP4XtQ3kW.yaml
  updated: 1757387542
- uid: gK2p9kXEiObQ
  type: groups
  name: null
  file: gK2p9kXEiObQ.yaml
  updated: 1757387542
- uid: R8gZjmES6YI5
  type: remote
  name: mihomo.yaml
  file: R8gZjmES6YI5.yaml
  desc: ''
  url: https://gh-proxy.org/raw.githubusercontent.com/shaoyouvip/free/main/mihomo.yaml
  selected:
  - name: 🚀 节点选择
    now: 🇺🇲 美国节点
  - name: 🚀 手动切换
    now: 🇺🇸US_8|1.7MB/s
  - name: ♻️ 自动选择
    now: sg|ab66|puddincat07@Telegram
  updated: 1783323226
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: m17flY2wkJGN
    script: s1KfOCTWvLUn
    rules: rsv811pc6MtC
    proxies: pIenP4XtQ3kW
    groups: gK2p9kXEiObQ
- uid: mxS2b0kO6yAb
  type: merge
  name: null
  file: mxS2b0kO6yAb.yaml
  updated: 1757387651
- uid: s0fpUyDWeOdo
  type: script
  name: null
  file: s0fpUyDWeOdo.js
  updated: 1757387651
- uid: rs8Xe4v35XPl
  type: rules
  name: null
  file: rs8Xe4v35XPl.yaml
  updated: 1757387651
- uid: p8ax70A8oeI8
  type: proxies
  name: null
  file: p8ax70A8oeI8.yaml
  updated: 1757387651
- uid: gyRqJBTRbuLB
  type: groups
  name: null
  file: gyRqJBTRbuLB.yaml
  updated: 1757387651
- uid: R676f6Ss0Sjy
  type: remote
  name: proxies.yaml
  file: R676f6Ss0Sjy.yaml
  desc: ''
  url: https://gh-proxy.org/raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml
  selected:
  - name: 🔰 节点选择
    now: nl|4a28|puddincat07@Telegram
  - name: ♻️ 自动选择
    now: gb|1593|puddincat07@Telegram
  - name: Proxy
    now: 🇺🇸 美国节点
  updated: 1783323227
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mxS2b0kO6yAb
    script: s0fpUyDWeOdo
    rules: rs8Xe4v35XPl
    proxies: p8ax70A8oeI8
    groups: gyRqJBTRbuLB
- uid: myAfmFwNURCc
  type: merge
  name: null
  file: myAfmFwNURCc.yaml
  updated: 1758015327
- uid: sXfLsW37QRjg
  type: script
  name: null
  file: sXfLsW37QRjg.js
  updated: 1758015327
- uid: rknzgllLIBI5
  type: rules
  name: null
  file: rknzgllLIBI5.yaml
  updated: 1758015327
- uid: pKE9L0oCTEsP
  type: proxies
  name: null
  file: pKE9L0oCTEsP.yaml
  updated: 1758015327
- uid: gJYIY1zOyjZs
  type: groups
  name: null
  file: gJYIY1zOyjZs.yaml
  updated: 1758015327
- uid: RzCWfAFvTeXa
  type: remote
  name: Jsnzkpg
  file: RzCWfAFvTeXa.yaml
  desc: ''
  url: https://gh-proxy.org/https://raw.githubusercontent.com/Jsnzkpg/Jsnzkpg/Jsnzkpg/Jsnzkpg
  selected:
  - name: 🚀 手动切换
    now: 🇫🇷FR_2|1.2MB/s
  - name: 🚀 节点选择
    now: 🚀 手动切换
  - name: Haita Cloud
    now: 下单地址https://kelayun.notepin.co
  - name: 🔰 节点选择
    now: kr|71a5|puddincat07@Telegram
  - name: 自动选择
    now: 官网地址https://kelayun.notepin.co
  - name: Proxy
    now: 🇰🇷 韩国节点
  updated: 1783323227
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: myAfmFwNURCc
    script: sXfLsW37QRjg
    rules: rknzgllLIBI5
    proxies: pKE9L0oCTEsP
    groups: gJYIY1zOyjZs
- uid: moAUGs2e9TRa
  type: merge
  name: null
  file: moAUGs2e9TRa.yaml
  updated: 1765712487
- uid: sKJEZZNHrno1
  type: script
  name: null
  file: sKJEZZNHrno1.js
  updated: 1765712487
- uid: rRmZafm16Wwk
  type: rules
  name: null
  file: rRmZafm16Wwk.yaml
  updated: 1765712487
- uid: pCh4xbwWseOr
  type: proxies
  name: null
  file: pCh4xbwWseOr.yaml
  updated: 1765712487
- uid: gjkHkO3KqD2G
  type: groups
  name: null
  file: gjkHkO3KqD2G.yaml
  updated: 1765712487
- uid: RX0QsdMN538J
  type: remote
  name: clash
  file: RX0QsdMN538J.yaml
  desc: ''
  url: https://gh-proxy.org//https://raw.githubusercontent.com/ts-sf/fly/main/clash
  selected:
  - name: 🚀 节点选择
    now: 🇯🇵JP日本 1.2MB/s
  - name: 🚀 手动切换
    now: 🇸🇬SG_3|1.7MB/s
  updated: 1783323227
  option:
    with_proxy: false
    self_proxy: false
    allow_auto_update: true
    merge: moAUGs2e9TRa
    script: sKJEZZNHrno1
    rules: rRmZafm16Wwk
    proxies: pCh4xbwWseOr
    groups: gjkHkO3KqD2G
- uid: mY3wtAG1LwFS
  type: merge
  name: null
  file: mY3wtAG1LwFS.yaml
  updated: 1773399680
- uid: sFx2zTnclq0F
  type: script
  name: null
  file: sFx2zTnclq0F.js
  updated: 1773399680
- uid: rvzhAziCnBAJ
  type: rules
  name: null
  file: rvzhAziCnBAJ.yaml
  updated: 1773399680
- uid: pcGFv8PJJyNg
  type: proxies
  name: null
  file: pcGFv8PJJyNg.yaml
  updated: 1773399680
- uid: g0WyTIUds2Ki
  type: groups
  name: null
  file: g0WyTIUds2Ki.yaml
  updated: 1773399680
- uid: RrsdrdP7Opk4
  type: remote
  name: yudou66.yaml
  file: RrsdrdP7Opk4.yaml
  desc: ''
  url: https://gh-proxy.org/raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/yudou66.yaml
  selected:
  - name: 🚀 节点选择
    now: 韩国(yudou789.top 玉豆免费节点)_1
  updated: 1783323226
  option:
    with_proxy: false
    self_proxy: false
    allow_auto_update: true
    merge: mY3wtAG1LwFS
    script: sFx2zTnclq0F
    rules: rvzhAziCnBAJ
    proxies: pcGFv8PJJyNg
    groups: g0WyTIUds2Ki
- uid: mfXNjaNyx19s
  type: merge
  name: null
  file: mfXNjaNyx19s.yaml
  updated: 1774265164
- uid: s6aakWpqIgXG
  type: script
  name: null
  file: s6aakWpqIgXG.js
  updated: 1774265164
- uid: rIQ1BDlmzNUi
  type: rules
  name: null
  file: rIQ1BDlmzNUi.yaml
  updated: 1774265164
- uid: p6EBiANjjnVa
  type: proxies
  name: null
  file: p6EBiANjjnVa.yaml
  updated: 1774265164
- uid: ge2fpr6vZZUj
  type: groups
  name: null
  file: ge2fpr6vZZUj.yaml
  updated: 1774265164
- uid: RClhMvILjc3E
  type: remote
  name: mihomo.yaml
  file: RClhMvILjc3E.yaml
  desc: ''
  url: https://gh-proxy.org/https://raw.githubusercontent.com/ovmvo/FreeSub/refs/heads/main/sub/permanent/mihomo.yaml
  selected:
  - name: Proxy
    now: 🇩🇪 德国节点
  updated: 1783294156
  option:
    with_proxy: false
    self_proxy: false
    allow_auto_update: true
    merge: mfXNjaNyx19s
    script: s6aakWpqIgXG
    rules: rIQ1BDlmzNUi
    proxies: p6EBiANjjnVa
    groups: ge2fpr6vZZUj
- uid: mHX3vk3nPwBP
  type: merge
  name: null
  file: mHX3vk3nPwBP.yaml
  updated: 1776765123
- uid: sOHhiSm1bUo9
  type: script
  name: null
  file: sOHhiSm1bUo9.js
  updated: 1776765123
- uid: rhU4BfztNqCG
  type: rules
  name: null
  file: rhU4BfztNqCG.yaml
  updated: 1776765123
- uid: p8o9wAvM8kV8
  type: proxies
  name: null
  file: p8o9wAvM8kV8.yaml
  updated: 1776765123
- uid: gW0rBOPDEVL6
  type: groups
  name: null
  file: gW0rBOPDEVL6.yaml
  updated: 1776765123
- uid: RDRAuhin84dF
  type: remote
  name: 魔戒.net
  file: RDRAuhin84dF.yaml
  desc: ''
  url: https://msub.xn--m7r52rosihxm.com/api/v1/client/subscribe?token=f84215e4a2f08b44eff91ee612d40f54
  selected:
  - name: 节点选择
    now: 美国LA-优化2-GPT
  - name: 🚀 手动切换
    now: 🇺🇸US_1|2.4MB/s
  extra:
    upload: 16652912281
    download: 108433938123
    total: 139586437120
    expire: 0
  updated: 1783323227
  option:
    with_proxy: false
    self_proxy: false
    update_interval: 60
    allow_auto_update: true
    merge: mHX3vk3nPwBP
    script: sOHhiSm1bUo9
    rules: rhU4BfztNqCG
    proxies: p8o9wAvM8kV8
    groups: gW0rBOPDEVL6
  home: https://mojie.app
